vsgc-acrp/acrpapp/urls.py
from django.urls import path, include
from . import views
from django.conf import settings
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static
# from django.contrib.auth import views
urlpatterns = [
    path('', views.index, name='index'),
    path('application/', views.application, name='application'),
    path('<int:pk>/', views.DesignAppDetailView.as_view(), name='designapp_detail'),
    path('login/',views.evaluator_login,name='evaluator_login'),
    path('acrp/', views.acrp, name='acrp'),
    path('process/', views.process, name='process'),
    path('process_detail/<str:ekey>/', views.process_detail, name='process_detail'),
    path('processed/', views.processed, name='processed'),
    path('processed_detail/<str:ekey>/', views.processed_detail, name='processed_detail'),
    path('Applicant/', views.Applicanturl, name='Applicanturl'),
    path('Applicantdetail/<str:ekey>/', views.Applicantdetail, name='Applicantdetail'),
    path('elogin/',views.user_login,name='user_login'),
    path('acrpmembers/', views.acrpmembers, name='acrpmembers'),
    path('evaluator/', views.evaluator, name='evaluator'),
    path('sorted/', views.sorted_id, name='sorted_id'),
    path('sorted_area/', views.sorted_area, name='sorted_area'),
    path('avgscore_designarea/', views.avgscore_designarea, name='avgscore_designarea'),
    path('avgscore/', views.avgscore, name='avgscore'),
    path('evaluator_detail/<str:ekey>/', views.evaluator_detail, name='evaluator_detail'),
    path('saved/<str:ekey>/', views.saved, name='saved'),
    path('completedsubmissions/', views.completedsubmissions, name='completedsubmissions'),
    path('completedsubmissions_detail/<str:ekey>/', views.completedsubmissions_detail, name='completedsubmissions_detail'),
    path('completedsubmissions_detail/<str:ekey>/<int:evalutor_id>/', views.sort_detail, name='sort_detail'),
    path('reedit/',views.reedit,name='reedit')
    
]

vsgc-acrp/acrpsite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('acrpapp.urls')),
    path('acrpapp/', include('acrpapp.urls')),
    path('acrpsite/', include('polls.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
    #path('media/',include('')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

vsgc-acrp/polls/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views
from django.views.generic import TemplateView
from django.contrib.auth.decorators import login_required, permission_required

urlpatterns = [
    path('index', views.index, name='index'),
    path('evaluator/search', views.search, name='search'),
    path('evaluator/saved_application/<int:Applicant_id>/', views.saved_application, name='saved_application'),
    path('evaluator/submit', views.submit, name='submit'),
    path('evaluator/submit_application/<int:Applicant_id>/', views.submit_application, name='submit_application'),
    path('advisor/<str:cheque_no>/<int:ref_num>', views.advisor, name='advisor'),
    path('', TemplateView.as_view(template_name='polls/urls.html')),
    path('elog/',views.user,name='user'),
    path('errorvisa/', TemplateView.as_view(template_name='polls/errorvisa.html')),

    # path('', TemplateView.as_view(template_name='polls/mainpage.html')),
    path('support/process', views.process, name='process'),
    path('support/process_detail/<int:Applicant_id>/', views.process_detail, name='process_detail'),
    path('support/processed', views.processed, name='processed'),
    path('support/processed_detail/<int:Applicant_id>/', views.processed_detail, name='processed_detail'),
    path('recom/<str:cheque_no>/<int:ref_num>', views.getrecommendations, name='getrecommendations'),
    path('support/', views.support,name='support'),
    path('openview', views.RecommendationsAllInternal, name=' RecommendationsAllInternal'),
    path('evaluators', views.evaluators,name='evaluators'),
    path('EvaluateSubmissions', views.EvaluateSubmissions, name='EvaluateSubmissions'),
    path('EvaluateSubmissions_detail/<int:Applicant_id>/', views.EvaluateSubmissions_detail, name='EvaluateSubmissions_detail'),
    path('EvaluateSubmissionsSaved_detail/<int:Applicant_id>/', views.EvaluateSubmissionsSaved_detail, name='EvaluateSubmissionsSaved_detail'),
    path('CompletedSubmissions', views.CompletedSubmissions, name='CompletedSubmissions'),
    path('compute_average_detail/<int:a_id>/', views.compute_average_detail, name='compute_average_detail'),
    path('log/',views.user_prof,name='user_prof'),
    path('support/compute_average', views.compute_average, name='compute_average'),
    path('support/compute_average_detail/<int:a_id>/', views.compute_average_detail, name='compute_average_detail'),
    path('support/enable',views.enableCompleteSubmissions,name='enableCompleteSubmissions'),
    path('support/averagescore',views.Average_score,name='Average_score'),
    path('support/lastname',views.Last_Name,name='Last_Name'),
    path('support/reedit',views.reedit,name='reedit'),
    path('support/adminupdatescore',views.adminupdatescore,name='updatescore'),
    path('support/evaluatorupdatescore',views.evaluatorupdatescore,name='evaluatorupdatescore'),
    path('support/reference_reminder',views.reference_reminder,name='reference_reminder'),
    path('support/EvaluateSubmissionsSaved_detail/<int:Applicant_id>/', views.EvaluateSubmissionsSaved_detail, name='EvaluateSubmissionsSaved_detail'),
    # path('acrp/support/userlogin/',views.user_login,name='user_login'),
    path('support/EvaluateSaved_detail/<int:Applicant_id>/<int:eval_id>/',views.EvaluateSaved_detail,name='EvaluateSaved_detail'),
    # path('acrp/support/EvaluateSaved_detail/<int:Applicant_id>/', views.EvaluateSaved_detail, name='EvaluateSaved_detail'),
    # path('acrp/login/', views.login, name ='login'), 



]

vsgc-acrp/acrpapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser 
from django.utils.translation import gettext_lazy
from django.conf import settings
from django.contrib.auth.models import User
from encrypted_id.models import EncryptedIDModel

# Create your models here.
class Applicant(EncryptedIDModel):
    Advisor1_FirstName=models.CharField(max_length=128,null=True)
    Advisor1_LastName=models.CharField(max_length=30,default=None,null=True)
    Advisor1_Department=models.CharField(max_length=100,default=None,null=True)
    Advisor1_Inst = models.CharField(max_length=128,default='')
    Advisor1_Street_Address=models.CharField(max_length=128,default=None,null=True)
    Advisor1_City=models.CharField(max_length=50,default=None,null=True)
    US_STATES = [('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')
    ]
    Advisor1_State=models.CharField(max_length=50,choices=US_STATES,default="",null=True)
    Advisor1_Zip_Code=models.IntegerField(max_length=13,default=None,null=True)
    Advisor1_Telephone=models.BigIntegerField(max_length=13,default=None,null=True)
    Advisor1_Fax=models.CharField(max_length=30,default=None,null=True)
    Advisor1_Email=models.EmailField(max_length=128,default=None,null=True)
    Advisor2_FirstName=models.CharField(max_length=128,default='',blank=True)
    Advisor2_LastName=models.CharField(max_length=30,default='',blank=True)
    Advisor2_Department=models.CharField(max_length=100,default='',blank=True)
    Advisor2_Inst = models.CharField(max_length=128,default='',blank=True)
    Advisor2_Street_Address=models.CharField(max_length=128,default='',blank=True)
    Advisor2_City=models.CharField(max_length=50,default='',blank=True)
    US___STATES = [('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')
    ]
    Advisor2_State=models.CharField(max_length=50,choices=US___STATES,default='',blank=True) 
    Advisor2_Zip_Code=models.CharField(max_length=20,default='',blank=True)
    Advisor2_Telephone=models.CharField(max_length=13,default='',blank=True)
    Advisor2_Fax=models.CharField(max_length=30,default='',blank=True)
    Advisor2_Email=models.EmailField(max_length=128,default='',blank=True)
    FAAAE = 'AE'
    FAAAM = 'AM'
    FAAAO = 'AO'
    FAARS = 'RS'
    DesignAreaChoices = [
        (FAAAE, 'Airport Environmental Interactions'),
        (FAAAM, 'Airport Management and Planning'),
        (FAAAO, 'Airport Operations and Maintenance'),
        (FAARS, 'Runway Safety/Runway Incursions/Runway Excursions'),
    ]
    design_area = models.CharField(max_length=50,choices=DesignAreaChoices,default="")
    Specific_Challenge=models.CharField(max_length=264,default="")
    Briefly_Describe=models.CharField(max_length=264,default="")
    team=[
             ('Student Team','Student Team'),
             ('Individual Student','Individual Student'),
         ]
    project_team=models.CharField(max_length=50,choices=team,default="")
    undertaken=[
               ('Design Class','Design Class'),
               ('Independent Study','Independent Study'),
               ('Student Society Chapter','Student Society Chapter'),
               ('Other','Other'),
               ]
    project_undertaken=models.CharField(max_length=50,choices=undertaken,default="")
    Other = models.CharField(max_length=100,blank=True)
    RADIOS = [
    ('Undergraduate','Undergraduate'),
    ('Graduate','Graduate'),
    ('Both','Both'),
    ]
    Students_Involved=models.CharField(
         max_length=50,
         choices=RADIOS,
         default="",
    )
    UG_level=models.CharField(max_length=50,blank=True)
    no_of_participants_UG=models.PositiveIntegerField(default="0")
    no_of_participants_G=models.PositiveIntegerField(default="0")
    no_of_participants_FA=models.PositiveIntegerField(default="0")
    no_of_participants_Other = models.CharField(max_length=200,blank=True)


    semester=models.CharField(max_length=50,default="",)
    created_at = models.DateField(auto_now_add=True, blank=True)






class DesignApp(EncryptedIDModel):
    Inst = models.CharField(max_length=128,default="",)
    title = models.CharField(max_length=200,default="")

    FAAAE = 'AE'
    FAAAM = 'AM'
    FAAAO = 'AO'
    FAARS = 'RS'
    DesignAreaChoices = [
        (FAAAE, 'Airport Environmental Interactions'),
        (FAAAM, 'Airport Management and Planning'),
        (FAAAO, 'Airport Operations and Maintenance'),
        (FAARS, 'Runway Safety/Runway Incursions/Runway Excursions'),
    ]
    design_area = models.CharField(max_length=3,choices=DesignAreaChoices,)
    Specific_Challenge=models.CharField(max_length=264,default="")

    RADIOS = [
    ('Undergraduate','Undergraduate'),
    ('Graduate','Graduate'),
    ('Both','Both'),
    ]
    Students_Involved=models.CharField(
         max_length=20,
         choices=RADIOS,
         default="",
    )
    Advisor1_FirstName=models.CharField(max_length=128,null=True)
    Advisor1_LastName=models.CharField(max_length=30,default=None,null=True)
    Advisor1_Department=models.CharField(max_length=100,default=None,null=True)
    Advisor1_Street_Address=models.CharField(max_length=128,default=None,null=True)
    Advisor1_City=models.CharField(max_length=50,default=None,null=True)
    US_STATES = [('AL', 'Alabama'), ('AK', 'Alaska'), ('AZ', 'Arizona'), ('AR', 'Arkansas'), ('CA', 'California'), ('CO', 'Colorado'), ('CT', 'Connecticut'), ('DE', 'Delaware'), ('DC', 'District of Columbia'), ('FL', 'Florida'), ('GA', 'Georgia'), ('HI', 'Hawaii'), ('ID', 'Idaho'), ('IL', 'Illinois'), ('IN', 'Indiana'), ('IA', 'Iowa'), ('KS', 'Kansas'), ('KY', 'Kentucky'), ('LA', 'Louisiana'), ('ME', 'Maine'), ('MD', 'Maryland'), ('MA', 'Massachusetts'), ('MI', 'Michigan'), ('MN', 'Minnesota'), ('MS', 'Mississippi'), ('MO', 'Missouri'), ('MT', 'Montana'), ('NE', 'Nebraska'), ('NV', 'Nevada'), ('NH', 'New Hampshire'), ('NJ', 'New Jersey'), ('NM', 'New Mexico'), ('NY', 'New York'), ('NC', 'North Carolina'), ('ND', 'North Dakota'), ('OH', 'Ohio'), ('OK', 'Oklahoma'), ('OR', 'Oregon'), ('PA', 'Pennsylvania'), ('RI', 'Rhode Island'), ('SC', 'South Carolina'), ('SD', 'South Dakota'), ('TN', 'Tennessee'), ('TX', 'Texas'), ('UT', 'Utah'), ('VT', 'Vermont'), ('VA', 'Virginia'), ('WA', 'Washington'), ('WV', 'West Virginia'), ('WI', 'Wisconsin'), ('WY', 'Wyoming')
    ]
    Advisor1_State=models.CharField(max_length=50,choices=US_STATES,default="",null=True)
    Advisor1_Zip_Code=models.IntegerField(max_length=13,default=None,null=True)
    Advisor1_Telephone=models.BigIntegerField(max_length=13,default=None,null=True)
    Advisor1_Fax=models.CharField(max_length=30,default=None,null=True)
    Advisor1_Email=models.EmailField(max_length=128,default=None,null=True)
    Advisor2_FirstName=models.CharField(max_length=128,default='',blank=True)
    Advisor2_LastName=models.CharField(max_length=30,default='',blank=True)
    Advisor2_Department=models.CharField(max_length=100,default='',blank=True)
    Advisor2_Street_Address=models.CharField(max_length=128,default='',blank=True)
    Advisor2_City=models.CharField(max_length=50,default='',blank=True)

vsgc-acrp/acrpapp/templates/acrpapp/Thankyou.html
<!DOCTYPE html>
<html>
<head>
	<title>Application SUbmitted</title>
</head>
<body>
	<div class="container">

		{{ f.created_at }}

		<h2>Thank you, {{ f.Advisor1_FirstName }} {{ f.Advisor1_LastName }}, for submitting the design package for the ACRP University Design Competition for Addressing Airport Needs.</h2>
	</div>

</body>
</html>

vsgc-acrp/acrpapp/templates/acrpapp/acrpmembers.html
<!DOCTYPE html>
<html>
<head>
	<title></title>
	<meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
</head>
<body>
<div class="container">
  <div class="jumbotron">
  <h4>Airport Cooperative Research Program (ACRP) University Design Competition for Addressing Airport Needs VSGC Support Members Page</h4>
</div>
<div style="text-align: center;">
<div style="display: inline-block; text-align: left;">
<ul>
<li><a href="/evaluator/">Evaluate Submissions</a><br></li>
<li><a href="/completedsubmissions/">View Completed Submissions</a></li>
</ul>
</div>
</div>
</div>
</body>
</html>

vsgc-acrp/acrpapp/templates/acrpapp/application.html
{% load crispy_forms_tags %}
<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
<style>
 .asteriskField {
    display: none;
}
</style>

</head>
<body>
	
	<div class="container">
  <div class="jumbotron">
  <h3><b>Notice of Intent to Participate in
Airport Cooperative Research Program (ACRP) University Design Competition for Addressing Airport Needs</b></h3>
</div>
  <p>
The deadline for Notices of Intent for the Fall semester is October 12, 2020 and for Spring semester, January 28, 2021. Individuals or teams commencing work after the September deadline can submit Notices of Intent at any time up to the January 28th deadline. Though not required, participants are encouraged to submit their Notice of Intent as early as possible so that the ACRP can assist them as needed with connections to airport operators as well as to partnering organization expertise. The Design Proposal is to be developed and written by students in compliance with the Competition Guidelines under the guidance of a faculty advisor. The Notice of Intent should be submitted by the faculty advisor. A separate Notice of Intent should be submitted for each individual and each team.<br><br>



All updates will be posted on the Competition Website:<a href="https://vsgc.odu.edu/acrpdesigncompetition/">https://vsgc.odu.edu/acrpdesigncompetition/</a></p>
<br><br>

<form method="post" enctype="multipart/form-data">
  {% csrf_token %}
  <div class="row">
  <div class="form-group col-md-6 mb-0">
  <i>{{ form.Advisor1_FirstName|as_crispy_field }}</i>
  </div>
  <div class="form-group col-md-6 mb-0">
  <i>{{ form.Advisor1_LastName|as_crispy_field }}</i>
  </div>
   <div class="form-group col-md-6 mb-0">
      <i>{{ form.Advisor1_Inst|as_crispy_field }}</i>
    </div>
  <div class="form-group col-md-6 mb-0">
  <i>{{ form.Advisor1_Department|as_crispy_field }}</i>
  </div>


  <div class="form-group col-md-6 mb-0">
    <i>{{ form.Advisor1_Street_Address|as_crispy_field }}</i>
  </div>
  <div class="form-group col-md-6 mb-0">
    <i>{{ form.Advisor1_City|as_crispy_field }}</i>
  </div>
  <div class="form-group col-md-6 mb-0">
     <i>{{ form.Advisor1_State|as_crispy_field }}</i>
  </div>
  <div class="form-group col-md-6 mb-0">
     <i>{{ form.Advisor1_Zip_Code|as_crispy_field }}</i>
  </div>
  <div class="form-group col-md-6 mb-0">
    <i>{{ form.Advisor1_Telephone|as_crispy_field }}</i>
  </div>
  <div class="form-group col-md-6 mb-0">
    <i>{{ form.Advisor1_Fax|as_crispy_field }}</i>
  </div>
  <div class="form-group col-md-6 mb-0">
    <i>{{ form.Advisor1_Email|as_crispy_field }}</i>
  </div>
  </div>

  <div class="row">
    <h4><b>Contact Information for Second Faculty Advisor (Optional):</b></h4>
  <div class="form-group col-md-6 mb-0">
    <i>{{ form.Advisor2_FirstName|as_crispy_field }}</i>
  </div>
  <div class="form-group col-md-6 mb-0">
    <i>{{ form.Advisor2_LastName|as_crispy_field }}</i>
  </div>
   <div class="form-group col-md-6 mb-0">
    <i>{{ form.Advisor2_Inst|as_crispy_field }}</i>
    </div>

  <div class="form-group col-md-6 mb-0">
    <i>{{ form.Advisor2_Department|as_crispy_field }}</i>
  </div>
  <div class="form-group col-md-6 mb-0">
    <i>{{ form.Advisor2_Street_Address|as_crispy_field }}</i>
  </div>
  <div class="form-group col-md-6 mb-0">
     <i>{{ form.Advisor2_City|as_crispy_field }}</i>
  </div>
  <div class="form-group col-md-6 mb-0">
     <i>{{ form.Advisor2_State|as_crispy_field }}</i>
  </div>
  <div class="form-group col-md-6 mb-0">
   <i>{{ form.Advisor2_Zip_Code|as_crispy_field }}</i>
  </div>
  <div class="form-group col-md-6 mb-0">
  <i>{{ form.Advisor2_Telephone|as_crispy_field }}</i>
  </div>
  <div class="form-group col-md-6 mb-0">
  <i>{{ form.Advisor2_Fax|as_crispy_field }}</i>
  </div>
  <div class="form-group col-md-6 mb-0">
  <i>{{ form.Advisor2_Email|as_crispy_field }}</i>
  </div>
  </div>

  <div class="row">
      <div class="form-group col-sm-8">
  <i>{{ form.design_area|as_crispy_field }}</i>
  </div>
  <div class="form-group col-sm-8">
   <i>{{ form.Specific_Challenge|as_crispy_field }}</i>
  </div>
  <div class="form-group col-sm-8">
  <i>{{ form.Briefly_Describe|as_crispy_field }}</i>
  </div>
   <div class="form-group col-sm-8">
  <i>{{ form.project_team|as_crispy_field }}</i>
  </div>
  <div class="form-group col-sm-8">
  <i>{{ form.project_undertaken|as_crispy_field }}</i>
  </div>
  <div class="form-group col-sm-8">
   <i>{{ form.Other|as_crispy_field }}</i>
  </div>
  <div class="form-group col-sm-8">
    <label><p>Level of Students Involved</p></label>
    <div class="row">
      <div class="col-6">
       {% for field in form.Students_Involved %}
        {{ field.label }} {{ field }}
    {% endfor %}
  </div>
</div>
  </div>
  <div class="form-group col-sm-8">
    <i>{{ form.UG_level|as_crispy_field }}</i>
  </div>
  <div class="form-group col-sm-8">
    <label><p>Estimated number of participants:</p></label>
  </div>
</div>

<div class="row">
      <div class="col col-lg-2">
      <label><p>Undergraduate</p></label>
    </div>
    <div class="col-6">
        {% for field in form.no_of_participants_UG %}
        {{ field.label }} {{ field }}
    {% endfor %}
  </div>
    </div>
<div class="row">
  <div class="col col-lg-2">
  <label><p>Graduate</p></label>
</div>
<div class="col-6">
       {% for field in form.no_of_participants_G %}
        {{ field.label }} {{ field }}
    {% endfor %}
  </div>
  </div>
 <div class="row">
  <div class="col col-lg-2">
    <label><p>Faculty Advisor</p></label>
  </div>
  <div class="col-6">
        {% for field in form.no_of_participants_FA %}
        {{ field.label }} {{ field }}
    {% endfor %}
  </div>
    </div>
  <div class="row">
  <div class="col col-lg-2">
      <label><p>Other</p></label>
    </div>
    <div class="col-6">
    {% for field in form.no_of_participants_Other %}
        {{ field.label }} {{ field }}
    {% endfor %}
  </div>
  </div>
  <div class="row">

   <div class="form-group col-sm-8">
  <i>{{ form.semester|as_crispy_field }}</i>
  </div>
  </div>
    <button type="submit" class="btn btn-primary btn-lg">Submit</button>
</form>
</div>
</body>
</html>

vsgc-acrp/acrpapp/templates/acrpapp/designapp_detail.html
<h1>{{ object.title }}</h1>

vsgc-acrp/acrpapp/templates/acrpapp/designapp_list.html
<h1>Articles</h1>
<ul>
{% for article in object_list %}
    <li><a href="{{article.id}}">{{ article.title }}</a> - {{ article.get_design_area_display }} </li>
{% empty %}
    <li>No submission yet.</li>
{% endfor %}
</ul>